import ipaddress

def is_rfc1918(ip: str) -> bool:
    try:
        obj = ipaddress.ip_address(ip)
    except ValueError:
        return False
    if obj.version != 4:
        return False  # RFC1918 is IPv4 only
    nets = [
        ipaddress.ip_network("10.0.0.0/8"),
        ipaddress.ip_network("172.16.0.0/12"),
        ipaddress.ip_network("192.168.0.0/16"),
    ]
    return any(obj in n for n in nets)


CATEGORY_TO_ROW = {
  "Adult": 2,
  "Advertisements": 3,
  "Alcohol": 4,
  "Animals and Pets": 5,
  "Arts": 6,
  "Astrology": 7,
  "Auctions": 8,
  "Business and Industry": 9,
  "Cannabis": 10,
  "Chat and Instant Messaging": 11,
  "Cheating and Plagiarism": 12,
  "Child Abuse Content": 13,
  "Cloud and Data Centers": 14,
  "Computer Security": 15,
  "Computers and Internet": 16,
  "Conventions, Conferences and Trade Shows": 17,
  "Cryptocurrency": 18,
  "Cryptomining": 19,
  "Dating": 20,
  "Digital Postcards": 21,
  "Dining and Drinking": 22,
  "DIY Projects": 23,
  "DNS-Tunneling": 24,
  "Dynamic and Residential": 25,
  "Dynamic DNS Provider": 26,
  "Education": 27,
  "Encrypted DNS": 28,
  "Entertainment": 29,
  "Extreme": 30,
  "Fashion": 31,
  "File Transfer Services": 32,
  "Filter Avoidance": 33,
  "Finance": 34,
  "Freeware and Shareware": 35,
  "Gambling": 36,
  "Games": 37,
  "Generative AI": 38,
  "Government and Law": 39,
  "Hacking": 40,
  "Hate Speech": 41,
  "Health and Medicine": 42,
  "Humor": 43,
  "Hunting": 44,
  "Illegal Activities": 45,
  "Illegal Downloads": 46,
  "Illegal Drugs": 47,
  "Infrastructure and Content Delivery Networks": 48,
  "Internet of Things": 49,
  "Internet Telephony": 50,
  "Job Search": 51,
  "Lingerie and Swimsuits": 52,
  "Lotteries": 53,
  "Military": 54,
  "Mobile Phones": 55,
  "Museums": 56,
  "Nature and Conservation": 57,
  "News": 58,
  "Non-governmental Organizations": 59,
  "Non-sexual Nudity": 60,
  "Not Actionable": 61,
  "Online Communities": 62,
  "Online Document Sharing and Collaboration": 63,
  "Online Meetings": 64,
  "Online Storage and Backup": 65,
  "Online Trading": 66,
  "Organizational Email": 67,
  "Paranormal": 68,
  "Parked Domains": 69,
  "Peer File Transfer": 70,
  "Personal Sites": 71,
  "Personal VPN": 72,
  "Photo Search and Images": 73,
  "Politics": 74,
  "Pornography": 75,
  "Private IP Addresses as Host": 76,
  "Professional Networking": 77,
  "Real Estate": 78,
  "Recipes and Food": 79,
  "Reference": 80,
  "Regional Restricted Sites (Germany)": 81,
  "Regional Restricted Sites (Great Britain)": 82,
  "Regional Restricted Sites (Italy)": 83,
  "Regional Restricted Sites (Poland)": 84,
  "Religion": 85,
  "SaaS and B2B": 86,
  "Safe for Kids": 87,
  "Science and Technology": 88,
  "Search Engines and Portals": 89,
  "Sex Education": 90,
  "Shopping": 91,
  "Social Networking": 92,
  "Social Science": 93,
  "Society and Culture": 94,
  "Software Updates": 95,
  "Sports and Recreation": 96,
  "Streaming Audio": 97,
  "Streaming Video": 98,
  "Terrorism and Violent Extremism": 99,
  "Tobacco": 100,
  "Transportation": 101,
  "Travel": 102,
  "URL Shorteners": 103,
  "Weapons": 104,
  "Web Cache and Archives": 105,
  "Web Hosting": 106,
  "Web Page Translation": 107,
  "Web-based Email": 108
}

BLOCKLISTS_FULLNAMES = {
  "general business": [
    "Filter Avoidance",
    "Personal VPN",
    "DNS-Tunneling",
    "Dynamic DNS Provider",
    "Encrypted DNS",
    "Peer File Transfer",
    "Illegal Downloads",
    "Cryptomining",
    "Hacking",
    "URL Shorteners",
    "Parked Domains",
    "Private IP Addresses as Host",
    "Child Abuse Content",
    "Terrorism and Violent Extremism",
    "Illegal Activities",
    "Extreme",
    "Hate Speech",
    "Pornography",
    "Adult",
    "Lingerie and Swimsuits",
    "Non-sexual Nudity",
    "Gambling",
    "File Transfer Services",
    "Online Storage and Backup",
    "Streaming Video",
    "Streaming Audio",
    "Social Networking",
    "Chat and Instant Messaging",
    "Cryptocurrency",
  ],

  "doctors office": [
    "Filter Avoidance",
    "Personal VPN",
    "DNS-Tunneling",
    "Dynamic DNS Provider",
    "Encrypted DNS",
    "Peer File Transfer",
    "Illegal Downloads",
    "Cryptomining",
    "Hacking",
    "URL Shorteners",
    "Parked Domains",
    "Private IP Addresses as Host",
    "Child Abuse Content",
    "Terrorism and Violent Extremism",
    "Illegal Activities",
    "Extreme",
    "Hate Speech",
    "Pornography",
    "Adult",
    "Lingerie and Swimsuits",
    "Non-sexual Nudity",
    "Gambling",
    "File Transfer Services",
    "Online Storage and Backup",
    "Social Networking",
    "Chat and Instant Messaging",
    "Streaming Video",
    "Streaming Audio",
  ],

  "cannabis org": [
    "Filter Avoidance",
    "Personal VPN",
    "DNS-Tunneling",
    "Dynamic DNS Provider",
    "Peer File Transfer",
    "Illegal Downloads",
    "Cryptomining",
    "Hacking",
    "URL Shorteners",
    "Parked Domains",
    "Private IP Addresses as Host",
    "Child Abuse Content",
    "Terrorism and Violent Extremism",
    "Illegal Activities",
    "Extreme",
    "Hate Speech",
    "Pornography",
    "Adult",
    "Lingerie and Swimsuits",
    "Non-sexual Nudity",
    "Gambling",
    "File Transfer Services",
    "Online Storage and Backup",
  ],

  "scientific tech org": [
    "Filter Avoidance",
    "Personal VPN",
    "DNS-Tunneling",
    "Dynamic DNS Provider",
    "Encrypted DNS",
    "Peer File Transfer",
    "Illegal Downloads",
    "Cryptomining",
    "URL Shorteners",
    "Parked Domains",
    "Private IP Addresses as Host",
    "Child Abuse Content",
    "Terrorism and Violent Extremism",
    "Illegal Activities",
    "Extreme",
    "Hate Speech",
    "Pornography",
    "Adult",
    "Lingerie and Swimsuits",
    "Non-sexual Nudity",
    "Gambling",
    "Hacking",
    "File Transfer Services",
    "Online Storage and Backup",
  ],

  "day care": [
    "Filter Avoidance",
    "Personal VPN",
    "DNS-Tunneling",
    "Dynamic DNS Provider",
    "Peer File Transfer",
    "Illegal Downloads",
    "Cryptomining",
    "Hacking",
    "URL Shorteners",
    "Parked Domains",
    "Private IP Addresses as Host",
    "Child Abuse Content",
    "Terrorism and Violent Extremism",
    "Illegal Activities",
    "Extreme",
    "Hate Speech",
    "Pornography",
    "Adult",
    "Lingerie and Swimsuits",
    "Non-sexual Nudity",
    "Gambling",
    "Dating",
    "Alcohol",
    "Tobacco",
    "Cannabis",
    "Weapons",
    "Social Networking",
    "Chat and Instant Messaging",
    "Streaming Video",
    "Streaming Audio",
  ],
}
